blogTitle = "håken.no"
authorName = "Håken Lid"
authorAbout = "Full stack web developer and designer"
linkPrefix = ""
github = "https://github.com/haakenlid"
codepen = "http://codepen.io/haakenlid/"
stackoverflow = "http://stackoverflow.com/users/1977847/?tab=profile"
twitter = "https://twitter.com/haakenlid"
